[package]
name = "neith"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-expand = "1.0.9"
r2d2 = "0.8.9"
r2d2_postgres = "0.18.1"
postgres = "0.19.1"